language:  python
python:
  - "2.7"
before_install:  
  - "sudo apt-get build-dep python-pygame -qq"
  - "sudo apt-get install mercurial -qq"
install:  "pip install -r requirements.txt"
script: "echo.py"
notifications:
  email: 
    - livysdad27@gmail.com
