language:  python
python:
  - "2.7"
before_install:  
  - "sudo apt-get -pp build-dep python-pygame"
  - "sudo apt-get -pp install mercurial"
install:  "pip install -r requirements.txt"
script: "echo.py"
notifications:
  email: 
    - livysdad27@gmail.com
