language:  python
python:
  - "2.7"
virtualenf:
  system_site_packages: true
before_install:  
  - "sudo apt-get update"
  - "sudo apt-get install python-pygame -qq"
  - "sudo apt-get install mercurial -qq"
  - "sudo apt-get install wine -qq"
install:  
  - "pip install -r requirements.txt"
script: 
  - "./echo.py"
notifications:
  email: 
    - livysdad27@gmail.com
